language: python

sudo: false

python:
  - "2.7"

cache:
  directories:
    - $HOME/.pip-cache

services:
  - memcached
  # - redis-server
  # - elasticsearch

env:
  - DJANGO_SETTINGS_MODULE=conf.settings.travis

install:
  - pip install --upgrade setuptools pip
  - pip install -r requirements/travis.txt --cache-dir $HOME/.pip-cache
  - npm install -g bower jspm grunt-cli
  - npm install

before_script:
  - mkdir log
  - bower install
  - jspm config registries.github.auth $GITHUBTOKEN
  - jspm install
  - src/manage.py collectstatic --noinput --link
  - src/manage.py systemjs_bundle

script:
  - coverage run src/manage.py test src  -v 2

after_success:
  - coveralls
  - codecov
