# http://stackoverflow.com/questions/20127174/how-can-i-update-node-js-and-install-grunt-bower-in-a-python-project-in-travis-c
language: python

python:
  - "2.7"

services:
  - memcached
  # - redis-server
  # - elasticsearch

install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install -r requirements/travis.txt
  - sudo add-apt-repository -y ppa:chris-lea/node.js
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs
  - sudo npm --registry http://registry.npmjs.eu/ install -g bower
  - sudo npm install

before_script:
  - mkdir log
  - bower install
  - jspm config endpoints.github.auth $gh-api-token
  - jspm install
  - src/manage.py collectstatic --noinput --link --settings=conf.settings.travis
  - src/manage.py systemjs_bundle --settings=conf.settings.travis

script:
  - coverage run src/manage.py test src/ --settings=conf.settings.travis -v 2

after_success:
  - coveralls
  - codecov
