language: python

python:
  - "2.7"

services:
  - memcached

env:
  - DJANGO=django<1.7

install:
  - pip install --upgrade setuptools --use-mirrors
  - pip install -r requirements/travis.txt --use-mirrors

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/archive/master.zip

before_script:
  - mkdir log

script:
  - coverage run manage.py test --settings=brouwers.settings.settings_travis -v 2

after_success:
  - coveralls
  - codecov
