language: python

python:
  - "2.7"

services:
  - memcached
  # - redis-server
  # - elasticsearch

env:
  - DJANGO=django<1.8

install:
  - pip install --upgrade setuptools --use-mirrors
  - pip install -r requirements/travis.txt --use-mirrors

matrix:
  allow_failures:
    - env: DJANGO=https://github.com/django/django/archive/master.zip

before_script:
  - mkdir log

script:
  - coverage run src/manage.py test src/ --settings=conf.settings.travis -v 2

after_success:
  - coveralls
  - codecov
